<?php
    $date = new DateTime();
?>

<script type="text/javascript" src="/assets/js/popper.min.js"></script>
<script type="text/javascript" src="/assets/js/bootstrap.min.js"></script>
<script type="text/javascript" src="/assets/vendor/autocomplete/autocomplete.js"></script>
<script type="text/javascript" src="/assets/vendor/tinymce/tinymce.js"></script>
<script type="text/javascript" src="/assets/vendor/list/list.js"></script>
<script type="text/javascript" src="/assets/vendor/validation/jquery.validate.min.js"></script>
<script type="text/javascript" src="/assets/vendor/validation/additional-methods.min.js"></script>
<script type="text/javascript" src="/assets/vendor/colorpicker/bootstrap-colorpicker.min.js"></script>
<script type="text/javascript" src="/assets/js/mdb.js?v=<?php echo $date->format("U"); ?>"></script>
<script type="text/javascript" src="/assets/vendor/select2/select2.full.min.js"></script>
<script type="text/javascript" src="/assets/vendor/sortable/sortable.min.js"></script>
<script type="text/javascript" src="/assets/js/site.js?v=<?php echo $date->format("U"); ?>"></script>
