<?php
?>
<script src="/assets/js/jquery-3.4.1.min.js"></script>
<script type="text/javascript" src="/assets/vendor/moment/moment.min.js"></script>
<script type="text/javascript" src="/assets/vendor/fullcalendar/fullcalendar.js"></script>
<script type="text/javascript" src="/assets/js/jquery-ui.min.js"></script>
<script type="text/javascript" src="/assets/vendor/fancybox/jquery.fancybox.min.js"></script>
