<?php
?>
<!DOCTYPE html>
<html lang="en">
<?php include VIEWS_PATH . '/layouts/includes/head.phtml'; ?>
<body class="trips-skin">
<?php include VIEWS_PATH . "/layouts/includes/body/header.phtml"; ?>
<main class=" m-0 p-0 h-auto" style="min-height:95vh;">
    <div class="page ">
        <?php echo $this->content(); ?>
    </div>
</main>
<?php include VIEWS_PATH . "/layouts/includes/body/footer.phtml"; ?>
<?php include VIEWS_PATH . "/layouts/includes/body/scripts_bottom.phtml"; ?>
</body>
</html>
